version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: stoom
      POSTGRES_PASSWORD: stoom
      POSTGRES_DB: stoom
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data